### ISSUE TITLE
Rename tool folder in project

### ISSUE THREAD

**Issue by v-bilous** [DJetCloud/djet-codegen#37]
This is the task to move to DJet brand

D.O.D.
- Rename folder `.difhub-codegen` in project root to `djet` (without `.` in the name)
- Create migration logic to change this folder in the existing Projects. While the first start with the new version folder should be changed to the new name automatically.

<img width="388" alt="Screenshot 2021-05-11 at 10 32 53" src="https://user-images.githubusercontent.com/19833841/117776436-3fa17c00-b244-11eb-860e-b62556950428.png">

**Comment by agentfan** [comment]
Should the DifHub menu in plagin be renamed too?
