### ISSUE TITLE
Upgrade spring boot version to 2.5.0

### ISSUE THREAD

**Issue by v-bilous** [DJetCloud/djet-codegen#61]
Let's update spring boot and related dependencies to the latest version.
https://spring.io/projects/spring-boot
- update spring boot version to 2.5.0 (current 2.4.2)
- check related dependencies versions: spring.dependency-management, plugin.spring, etc.

**Comment by agentfan** [comment]
spring.dependency-management 1.0.11.RELEASE, jacoco 0.8.7
