### ISSUE TITLE
Could not find org.junit.jupiter:junit-jupiter-engine

### ISSUE THREAD

**Issue by dimitrikvirik** [DJetCloud/djet-codegen#79]
I tried to open project and gradle say, that  can't find org.junit.jupiter:junit-jupiter-engine, wich is required by three plugins
![image](https://user-images.githubusercontent.com/63537879/141690528-04798b27-b0bd-40ba-81d9-01f34b1c4039.png)

**Comment by v-bilous** [comment]
hi @dimitrikvirik, please add information about your IDE and JDK, steps to reproduce. 
an example https://github.com/mplushnikov/lombok-intellij-plugin/issues/1075
